name: Build and Deploy to GKE

on:
- push

env:
  GKE_PROJECT: kbh-billeder
  IMAGE: kbh-billeder
  CLUSTER_NAME: kbh-billeder-cluster-1
  ZONE: europe-west1-b
  CONTAINER_REGISTRY: eu.gcr.io

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup gcloud
      uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        project_id: ${{ env.GKE_PROJECT }}

    - name: Setup docker
      run: gcloud --quiet auth configure-docker $CONTAINER_REGISTRY


    - name: Setup kubectl
      uses: google-github-actions/get-gke-credentials@v0.2.1
      with:
        credentials: ${{ secrets.GKE_SA_KEY }}
        cluster_name: ${{ env.CLUSTER_NAME }}
        location: ${{ env.ZONE }}

    - name: Build image
      run: |-
        cat << EOF > .env
        DISABLE_NOTIFIER="true"
        NODE_ENV=beta
        EOF
        docker build \
          --tag "$CONTAINER_REGISTRY/$GKE_PROJECT/$IMAGE:$GITHUB_SHA" \
          --tag "$CONTAINER_REGISTRY/$GKE_PROJECT/$IMAGE:latest" \
          .

    - name: Publish docker image
      if: ${{ github.ref == 'refs/heads/master' }}
      run: |-
        docker push "$CONTAINER_REGISTRY/$GKE_PROJECT/$IMAGE" --all-tags

    - name: Deploy to beta environment
      if: ${{ github.ref == 'refs/heads/master' }}
      run: |-
        kubectl -n beta set env deployment/frontend DEPLOYED_AT="`date`"
